import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className=" mx-auto">
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
